server:
  port: 8080
db:
  username: postgres
  password: postgres
  hostname: localhost
  name: macro
  port: 5432
api:
  key: jJ5oUIbJ4BvrTwgSx5ai5tDydhBRbvrwlB84GRMr

spring:
  datasource:
    url: jdbc:postgresql://${db.hostname}:${db.port}/${db.name}
    driverClassName: org.postgresql.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect