CREATE TABLE public.consumption
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    desired_daily_intake INTEGER,
    creation_date TIMESTAMP,

    CONSTRAINT consumption_pkey PRIMARY KEY (id)
);