CREATE TABLE public.meal
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    consumption_id INTEGER NOT NULL,

    CONSTRAINT meal_pkey PRIMARY KEY (id),
    CONSTRAINT fk_meal_consumption FOREIGN KEY (consumption_id) REFERENCES public.consumption (id)
);