CREATE TABLE public.recipe
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    calories INTEGER,
    consumption_id INTEGER NOT NULL,

    CONSTRAINT recipe_pkey PRIMARY KEY (id),
    CONSTRAINT fk_recipe_consumption FOREIGN KEY (consumption_id) REFERENCES public.consumption (id)
);