CREATE TABLE public.ingredient
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    quantity INTEGER,
    carbohydrates INTEGER,
    proteins INTEGER,
    fats INTEGER,
    fibers INTEGER,
    recipe_id INTEGER NOT NULL,
    meal_id INTEGER NOT NULL,

    CONSTRAINT ingredient_pkey PRIMARY KEY (id),
    CONSTRAINT ingredient_name_key UNIQUE (name),
    CONSTRAINT fk_ingredient_recipe FOREIGN KEY (recipe_id) REFERENCES public.recipe (id),
    CONSTRAINT fk_ingredient_meal FOREIGN KEY (meal_id) REFERENCES public.meal (id)
);